# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Unsplash-Images' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Unsplash-Images
  pod 'Alamofire'
  pod 'ReachabilitySwift'
  pod 'Firebase/Core'
  pod 'Firebase/Auth'

end
